In [ ]:
import numpy as np

In [4]:
test_array = np.array([1, 2, 3, 4])
print(test_array)
print(test_array.dtype)
print(test_array.ndim)

[1 2 3 4]
int64
1


In [6]:
# 4 rows, 3 columns
matrix_zeros = np.zeros((4, 3))
print(matrix_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
# boolean mask
m2D = 10 * np.random.rand(5, 5).round(2)
# find all entries x with x > 3
m2DBoolean = m2D > 3
# results in 1D-array
print(m2D[m2DBoolean])

[5.3 7.3 9.9 8.5 7.4 8.5 3.9 9.8 5.2 3.2 4.7 4.3 5.6 5.8]


In [83]:
first = np.zeros((4, 4))
second = first
# first and second point to the same memory
first[1,...] = 1
print(second)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [86]:
arr = np.zeros((3, 3))
arr[0,:] = 1
print(arr)
# arr.reshape(1, 9) would lead to a 2D-matrix
# true 1D-array
print(arr.reshape(9))
try:
    print(arr.reshape(3, 4))
except:
    print("New shape has to have the same amount of cells as the old shape.")

[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 0. 0. 0. 0. 0. 0.]
New shape has to have the same amount of cells as the old shape.


In [95]:
Test2D1 = np.arange(9).reshape(3,3)
print(Test2D1, '\n')

Test2D2 = 2*np.arange(9).reshape(3,3)
print(Test2D2, '\n')

Test2D3 = 3*np.arange(9).reshape(3,3)
print(Test2D3, '\n')

#concatenation only works on matrices, not arrays (would need reshaping to 1xn)
# axis = 0 => rows are connected (hstack() works, too)
# axis = 1 => columns are connected (vstack() works, too)
Test2D = np.concatenate((Test2D1,Test2D2,Test2D3),axis=1)
print(Test2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]] 

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

[[ 0  1  2  0  2  4  0  3  6]
 [ 3  4  5  6  8 10  9 12 15]
 [ 6  7  8 12 14 16 18 21 24]]
